# Base configuration for the quantitative framework
# This file contains default settings that apply to all environments

# Application settings
debug: false
secret_key: "change-me-in-production"

# Database configuration
database:
  host: "localhost"
  port: 5432
  name: "quantframework"
  user: "postgres"
  password: ""
  pool_size: 10
  max_overflow: 20

# Data source configurations
data_sources:
  yahoo_finance:
    enabled: true
    rate_limit: 2000
    timeout: 30
    retry_attempts: 3
    retry_delay: 1
  
  alpha_vantage:
    enabled: false
    api_key: ""
    rate_limit: 500
    timeout: 30
    base_url: "https://www.alphavantage.co/query"
  
  iex_cloud:
    enabled: false
    api_key: ""
    base_url: "https://cloud.iexapis.com/stable"
    timeout: 30
  
  quandl:
    enabled: false
    api_key: ""
    base_url: "https://www.quandl.com/api/v3"
    timeout: 30

# Risk management limits
risk_limits:
  max_position_size: 0.05        # 5% maximum position size
  max_sector_exposure: 0.20      # 20% maximum sector exposure
  var_limit: 0.02                # 2% VaR limit
  max_drawdown_limit: 0.15       # 15% maximum drawdown
  concentration_limit: 0.10      # 10% concentration limit
  leverage_limit: 1.0            # No leverage by default

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/quantframework.log"
  structured_file_path: "logs/quantframework.json"
  max_file_size: 10485760        # 10MB
  backup_count: 5
  console_output: true

# Cache configuration
cache:
  enabled: true
  backend: "memory"              # memory, redis, file
  ttl: 3600                      # 1 hour default TTL
  max_size: 1000                 # Maximum number of cached items
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0

# Feature engineering settings
feature_engineering:
  default_lookback_periods: [5, 10, 20, 50, 200]
  technical_indicators:
    rsi_period: 14
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    bollinger_period: 20
    bollinger_std: 2
  
  # Data quality thresholds
  data_quality:
    min_data_points: 252          # Minimum 1 year of data
    max_missing_ratio: 0.05       # Maximum 5% missing data
    outlier_threshold: 3.0        # 3 standard deviations

# Portfolio optimization settings
portfolio_optimization:
  default_method: "mean_variance"
  rebalance_frequency: "monthly"
  transaction_cost: 0.001        # 0.1% transaction cost
  min_weight: 0.01               # 1% minimum weight
  max_weight: 0.20               # 20% maximum weight

# Backtesting settings
backtesting:
  initial_capital: 100000        # $100,000 initial capital
  commission: 0.001              # 0.1% commission
  slippage: 0.0005               # 0.05% slippage
  market_impact: 0.0001          # 0.01% market impact

# Machine learning settings
machine_learning:
  default_test_size: 0.2
  cross_validation_folds: 5
  random_state: 42
  early_stopping_patience: 10
  
  # Model hyperparameters
  lstm:
    sequence_length: 60
    units: 128
    dropout_rate: 0.3
    learning_rate: 0.001
    batch_size: 32
    epochs: 100

# Performance monitoring
monitoring:
  metrics_collection: true
  performance_alerts: true
  health_check_interval: 300     # 5 minutes
  
# Security settings
security:
  password_min_length: 8
  session_timeout: 3600          # 1 hour
  max_login_attempts: 5
  lockout_duration: 900          # 15 minutes