# Production environment configuration
# Overrides base configuration for production

debug: false

# Production database settings
database:
  host: "${DB_HOST}"
  port: "${DB_PORT:5432}"
  name: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  pool_size: 20
  max_overflow: 40

# Production logging - less verbose, structured logs
logging:
  level: "INFO"
  console_output: false          # No console output in production
  file_path: "/var/log/quantframework/app.log"
  structured_file_path: "/var/log/quantframework/app.json"
  max_file_size: 52428800        # 50MB
  backup_count: 10

# Strict risk limits for production
risk_limits:
  max_position_size: 0.03        # 3% maximum position size
  max_sector_exposure: 0.15      # 15% maximum sector exposure
  var_limit: 0.015               # 1.5% VaR limit
  max_drawdown_limit: 0.10       # 10% maximum drawdown
  concentration_limit: 0.08      # 8% concentration limit

# Production data sources
data_sources:
  yahoo_finance:
    enabled: true
    rate_limit: 2000
  
  alpha_vantage:
    enabled: true
    # API key from environment variable
  
  iex_cloud:
    enabled: true
    # API key from environment variable
  
  quandl:
    enabled: true
    # API key from environment variable

# Redis cache for production
cache:
  enabled: true
  backend: "redis"
  ttl: 3600                      # 1 hour
  max_size: 10000
  redis_host: "${REDIS_HOST:localhost}"
  redis_port: "${REDIS_PORT:6379}"
  redis_db: 0

# Strict data quality requirements
feature_engineering:
  data_quality:
    min_data_points: 504         # Minimum 2 years of data
    max_missing_ratio: 0.02      # Maximum 2% missing data
    outlier_threshold: 2.5       # More conservative outlier detection

# Production portfolio settings
portfolio_optimization:
  transaction_cost: 0.002        # Higher transaction costs
  min_weight: 0.005              # 0.5% minimum weight
  max_weight: 0.15               # 15% maximum weight

# Production backtesting
backtesting:
  initial_capital: 1000000       # $1M initial capital
  commission: 0.002              # 0.2% commission
  slippage: 0.001                # 0.1% slippage
  market_impact: 0.0002          # 0.02% market impact

# Production ML settings
machine_learning:
  lstm:
    epochs: 200                  # More epochs for better training
    batch_size: 64               # Larger batch size
    early_stopping_patience: 20

# Production monitoring
monitoring:
  metrics_collection: true
  performance_alerts: true
  health_check_interval: 60      # 1 minute

# Enhanced security for production
security:
  password_min_length: 12
  session_timeout: 1800          # 30 minutes
  max_login_attempts: 3
  lockout_duration: 1800         # 30 minutes